import { Artwork, Collection } from './types';

export const ACCENT_COLOR = '#bdcda7';

export const COLLECTIONS: Collection[] = [
  { id: 'c1', name: 'Ethereal Structures', slug: 'ethereal', description: 'Explorations in digital architecture.' },
  { id: 'c2', name: 'Void Portraits', slug: 'void', description: 'Character studies in negative space.' },
  { id: 'c3', name: 'Industrial Decay', slug: 'industrial', description: 'Texture and form in abandoned spaces.' },
];

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: 'Adelaide Portrait',
    slug: 'adelaide-portrait',
    year: '2024',
    medium: 'Photography',
    dimensions: 'Digital',
    description: 'Portrait photography.',
    collectionId: 'c2',
    tags: ['Photography', 'Portrait'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/AdelaidePortrait.jpg',
    galleryMedia: [],
  },
  {
    id: '2',
    title: 'Work 1',
    slug: 'work-1',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/1734587244809-61709c4c-6f2f-4670-91ec-3b7e27d8a45djpeg_1.jpg',
    galleryMedia: [],
  },
  {
    id: '3',
    title: 'Work 2',
    slug: 'work-2',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/1734587275315-aafd5d4d-02d4-44cb-975e-d957a18527c0jpeg_1.jpg',
    galleryMedia: [],
  },
  {
    id: '4',
    title: 'Work 3',
    slug: 'work-3',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20241217_075546.jpg',
    galleryMedia: [],
  },
  {
    id: '5',
    title: 'Work 4',
    slug: 'work-4',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20241217_075555.jpg',
    galleryMedia: [],
  },
  {
    id: '6',
    title: 'Work 5',
    slug: 'work-5',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20241217_075605.jpg',
    galleryMedia: [],
  },
  {
    id: '7',
    title: 'Work 6',
    slug: 'work-6',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20241217_132809.jpg',
    galleryMedia: [],
  },
  {
    id: '8',
    title: 'Work 7',
    slug: 'work-7',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20241217_132818.jpg',
    galleryMedia: [],
  },
  {
    id: '9',
    title: 'Work 8',
    slug: 'work-8',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20241217_132838.jpg',
    galleryMedia: [],
  },
  {
    id: '10',
    title: 'Work 9',
    slug: 'work-9',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20241217_132857.jpg',
    galleryMedia: [],
  },
  {
    id: '11',
    title: 'Work 10',
    slug: 'work-10',
    year: '2024',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20241218_213931.jpg',
    galleryMedia: [],
  },
  {
    id: '12',
    title: 'Work 11',
    slug: 'work-11',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250521_152552.jpg',
    galleryMedia: [],
  },
  {
    id: '13',
    title: 'Work 12',
    slug: 'work-12',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250530_103704.jpg',
    galleryMedia: [],
  },
  {
    id: '14',
    title: 'Work 13',
    slug: 'work-13',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191805.jpg',
    galleryMedia: [],
  },
  {
    id: '15',
    title: 'Work 14',
    slug: 'work-14',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191827.jpg',
    galleryMedia: [],
  },
  {
    id: '16',
    title: 'Work 15',
    slug: 'work-15',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191827_edited.jpg',
    galleryMedia: [],
  },
  {
    id: '17',
    title: 'Work 16',
    slug: 'work-16',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191838.jpg',
    galleryMedia: [],
  },
  {
    id: '18',
    title: 'Work 17',
    slug: 'work-17',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191838_edited.jpg',
    galleryMedia: [],
  },
  {
    id: '19',
    title: 'Work 18',
    slug: 'work-18',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191843.jpg',
    galleryMedia: [],
  },
  {
    id: '20',
    title: 'Work 19',
    slug: 'work-19',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191847.jpg',
    galleryMedia: [],
  },
  {
    id: '21',
    title: 'Work 20',
    slug: 'work-20',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191852.jpg',
    galleryMedia: [],
  },
  {
    id: '22',
    title: 'Work 21',
    slug: 'work-21',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191930.jpg',
    galleryMedia: [],
  },
  {
    id: '23',
    title: 'Work 22',
    slug: 'work-22',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191930_edited.jpg',
    galleryMedia: [],
  },
  {
    id: '24',
    title: 'Work 23',
    slug: 'work-23',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191939.jpg',
    galleryMedia: [],
  },
  {
    id: '25',
    title: 'Work 24',
    slug: 'work-24',
    year: '2025',
    medium: 'Mixed Media',
    dimensions: 'Digital',
    description: 'Artwork exploration.',
    collectionId: 'c1',
    tags: ['Mixed Media'],
    availability: 'for_sale',
    featured: true,
    heroMedia: '/Site Files/20250602_191939_edited.jpg',
    galleryMedia: [],
  },
];