import { Artwork, Collection } from './types';

export const ACCENT_COLOR = '#00C896';

export const COLLECTIONS: Collection[] = [
  { id: 'c1', name: 'Ethereal Structures', slug: 'ethereal', description: 'Explorations in digital architecture.' },
  { id: 'c2', name: 'Void Portraits', slug: 'void', description: 'Character studies in negative space.' },
  { id: 'c3', name: 'Industrial Decay', slug: 'industrial', description: 'Texture and form in abandoned spaces.' },
];

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: 'Neon Silence',
    slug: 'neon-silence',
    year: '2023',
    medium: 'Digital 3D Render',
    dimensions: '4000x5000px',
    description: 'A study of light interactions in a vacuum environment. The piece explores the concept of silence as a visual medium.',
    collectionId: 'c1',
    tags: ['3D', 'Abstract', 'Light'],
    availability: 'for_sale',
    featured: true,
    heroMedia: 'https://picsum.photos/id/20/1200/1600',
    galleryMedia: ['https://picsum.photos/id/21/800/600', 'https://picsum.photos/id/22/800/600'],
  },
  {
    id: '2',
    title: 'Chrome Heart',
    slug: 'chrome-heart',
    year: '2024',
    medium: 'Oil on Canvas',
    dimensions: '48x48 inches',
    description: 'Traditional techniques applied to futuristic subjects. Layers of oil glaze create a metallic sheen.',
    collectionId: 'c2',
    tags: ['Painting', 'Portrait'],
    availability: 'sold',
    featured: true,
    heroMedia: 'https://picsum.photos/id/30/1200/1600',
    galleryMedia: ['https://picsum.photos/id/31/800/600'],
  },
  {
    id: '3',
    title: 'Fragment 09',
    slug: 'fragment-09',
    year: '2022',
    medium: 'Mixed Media',
    dimensions: '24x36 inches',
    description: 'Deconstructed forms found in urban environments.',
    collectionId: 'c3',
    tags: ['Mixed Media', 'Urban'],
    availability: 'for_sale',
    featured: true,
    heroMedia: 'https://picsum.photos/id/42/1200/1600',
    galleryMedia: [],
  },
  {
    id: '4',
    title: 'Orbital Decay',
    slug: 'orbital-decay',
    year: '2023',
    medium: 'Generative Video',
    dimensions: '1920x1080',
    description: 'Algorithmic deterioration of a perfect sphere over 10,000 frames.',
    collectionId: 'c1',
    tags: ['Generative', 'Video'],
    availability: 'nfs',
    featured: false,
    heroMedia: 'https://picsum.photos/id/88/1600/900',
    galleryMedia: [],
  },
  {
    id: '5',
    title: 'Ghost Machine',
    slug: 'ghost-machine',
    year: '2024',
    medium: 'Photography',
    dimensions: 'Digital',
    description: 'Long exposure photography of machinery in motion.',
    collectionId: 'c3',
    tags: ['Photo', 'Industrial'],
    availability: 'for_sale',
    featured: true,
    heroMedia: 'https://picsum.photos/id/96/1200/1600',
    galleryMedia: [],
  },
   {
    id: '6',
    title: 'Static Field',
    slug: 'static-field',
    year: '2023',
    medium: 'Digital',
    dimensions: '4000x4000px',
    description: 'Visualizing electromagnetic interference.',
    collectionId: 'c1',
    tags: ['Abstract', 'Digital'],
    availability: 'for_sale',
    featured: false,
    heroMedia: 'https://picsum.photos/id/110/1000/1000',
    galleryMedia: [],
  },
];